### ISSUE TITLE
Negated character classes

### ISSUE THREAD

**Issue by mingodad** [ChrisHixon/chpeg#13]
Trying to parse EBNF files I'm getting error when trying to parse then so I trimmed down the grammar and found that the problem is with quoted strings recognition:

Minimal grammar (that works on peglib playground but chpeg can't handle):
```
Grammar <-
	 StringLiteral* ! .

WS <-
	 '\t'
	/ '\n'
	/ '\r'
	/ ' '

StringLiteral <-
	 ( ( '"' [^"]* '"' ) / ( "'" [^']* "'" ) ) WS*
```
Input file:
```
'::='

```
chpeg output:
```
examples/peg_parse_file ebnf-min.peg test.ebnf
parse ok.
Grammar file compiled successfully. Parser returned: 135
parse failed with result: -1
Unexpected "character" in Grammar at offset 1
```

**Comment by mingodad** [comment]
After looking at it a bit more the problem seems to be with the `CHRCLS` not taking in account the repetition zero or more `*` and issuing the error.

**Comment by mingodad** [comment]
In the end it's that `chpeg` doesn't support `^` negated charset classes.

**Comment by ChrisHixon** [comment]
Yeah `^ negated charset classes` is not standard PEG syntax and chpeg doesn't support that extension.
The standard PEG way is `!["].`

```
Grammar <- (StringLiteralStdPEG WS*)+ ! .

WS <-
	 '\t'
	/ '\n'
	/ '\r'
	/ ' '

StringLiteralStdPEG <-
	 ( ( '"' (!["].)* '"' ) / ( "'" (!['].)* "'" ) )
```
I'm not sure why everyone wants to put whitespace into the terminals - I see that in many grammars. Why capture the whitespace in the terminal? I move WS to a higher level like above.

**Comment by mingodad** [comment]
I just replaces all negated classes by the standard `peg` way and my implementation of `HexChar` is working and the grammar  for EBNF now parses the example input.

How hard would be to implement `^` negated classes or emit a warning to alert users ?
It's handy to easy convert from other formats.

**Comment by mingodad** [comment]
And now I understand what you've commented elsewhere about spaces in captures:
```
StringLiteral {L} <-
	 ( ( '"' (!'"' .)* '"' ) / ( "'" (!"'" .)* "'" ) ) WS*
```
Output:
```
   743      4     10 |   L |       StringLiteral "']'\n"
```
The `peglib` way solves this problem:
```
StringLiteral <-
	 <( ( '"' (!'"' .)* '"' ) / ( "'" (!"'" .)* "'" ) )> WS*
```
Output:
```
            - StringLiteral (']')
```

**Comment by ChrisHixon** [comment]
It probably would not be hard to add negated char classes. I kind of have mixed feeling about syntax extensions. While many are nice, where does it end? Each one expands what is a meant to be a small simple library. I don't know about warning about things that are not even PEG in the first place - oops you might be trying to use an extension some other library has? I don't think I want to get into that territory. However if I do decide to add extensions, optional warnings might be nice, or some other way to check that PEG extensions are being used.
Here's another idea: write something that converts PEG extensions to standard PEG.

**Comment by ChrisHixon** [comment]
I've been considering adding the `"caseinsensitive"i` syntax (I know you have created an implementation of this); however I'm also thinking of a few other case insensitive things.

It would make sense to allow back-references to compare case insensitively. So start tag `<a>` could have an ending `</A>` if desired. I'm thinking of using `:i` postfix. So capture/mark: `$tag<TAGNAME>` reference: `$tag:i`.

Another thing I'm pondering is dictionaries like cpp-peglib. I'm thinking users might want to match those case intensively too.

Or perhaps even match entire rules or parenthesized groups case insensitively.

So the `:i` postfix could apply to many things. It would make sense to change the literal syntax to use `:i` as well. Another thought is to add a rule Option `{i}`, not to be confused with `{I}`. Also `:postfix` might make sense for other options other than `i` later.

**Comment by ChrisHixon** [comment]
Negated char classes implemented here: https://github.com/ChrisHixon/chpeg/commit/34b3194b506881c9c0a32a9490f5bbdae45a88f9

**Comment by ChrisHixon** [comment]
Closing this, since it's been implemented. Other ideas discussed in here are in my notes.
