### ISSUE TITLE
Here is an example of a C99 parser that is not working properly on `chpeg` but does work on `cpp-peglib` playgorund https://yhirose.github.io/cpp-peglib.

### ISSUE THREAD

**Issue by ChrisHixon** [ChrisHixon/chpeg#2]
Here is an example of a C99 parser that is not working properly on `chpeg` but does work on `cpp-peglib` playgorund https://yhirose.github.io/cpp-peglib.

On `cpp-peglib` playground copy and paste `c99-mouse-cpp-peglib.peg` in the `Grammar` and `c99-mouse.peg.pp.c` on `Source Code`.
```
 c99-mouse-cpp-peglib.peg # is the same as c99-mouse.peg with some `~` Ignore flags
 c99-mouse.peg
 c99-mouse.peg.pp.c
```
With chpeg:
```
chpeg c99-mouse.peg c99-mouse.peg.pp.c 
parse ok.
Grammar file compiled successfully. Parser returned: 19382
parse failed with result: -1
Expected SEMI in Declaration at offset 3092

```
[c99-mouse.zip](https://github.com/ChrisHixon/chpeg/files/8647661/c99-mouse.zip)

_Originally posted by @mingodad in https://github.com/ChrisHixon/chpeg/issues/1#issuecomment-1120475606_

**Comment by mingodad** [comment]
To debug grammars/parsing would be nice to have a trace of the VM execution and also possibly be able to use/have something like https://github.com/fasterthanlime/pegviz

**Comment by mingodad** [comment]
I found that you have a kind of VM trace commented in Parser_parse, I'm trying with this variation:
```
int Parser_parse(Parser *self, const unsigned char *input, int size, int verbose)
{
...
        op = instructions[pc] & 0xff;
        arg = instructions[pc] >> 8;
        
        if(verbose) {
            const char *ident_name;
            switch(op) {
                case IDENT:
                case IFAIL:
                case ISUCC:
                        ident_name = self->def_names[arg];
                        fprintf(stderr, "=CNT\t%lld\tOFS\t%d\tPC\t%d\tOP\t%d\t%d\t%s %s\n", cnt, offset, pc, op, arg, OpNames[op], ident_name);
                    break;

                default:
                    ident_name = "";
            }
            //fprintf(stderr, "=CNT\t%lld\tPC\t%d\tOP\t%d\t%d\t%s %s\n", cnt, pc, op, arg, OpNames[op], ident_name);
        }
...
}
```

**Comment by mingodad** [comment]
And here is the reduced input file that fails:
```
typedef void * __timer_t;
```
Output:
```
parse ok.
parse failed with result: -1
Expected SEMI in Declaration at offset 13 in line 1:13
```

**Comment by ChrisHixon** [comment]
It fails even for `void * __timer_t;`:
```
parse failed with result: -1
Expected SEMI in Declaration at offset 5
```
Any ideas what the problem might be? I used your VM trace code but haven't spotted anything obvious yet. I'll have to dig deeper.

Can we eliminate things like PEG extensions used by other parsers? This comment is a little concerning:
`#  Requires semantics class to process Typedefs.`

Is it even possible to parse C using PEG without adding something like this for typedefs?

**Comment by mingodad** [comment]
With the help of https://yhirose.github.io/cpp-peglib playground I could trim down the grammar even more, when removing the `LongComment` that is not referenced anywhere anymore then it parses fine, maybe with this minimal grammar and the previous clue you can have any insight of what is happening now.
```
TranslationUnit <- Spacing ( ExternalDeclaration / SEMI ) * EOT

ExternalDeclaration <- Declaration

Declaration <- DeclarationSpecifiers InitDeclaratorList? SEMI

DeclarationSpecifiers
   <- (  TypeSpecifier
      )+

InitDeclaratorList <- InitDeclarator

InitDeclarator <- Declarator

TypeSpecifier
   <- VOID

Declarator <- Pointer? DirectDeclarator

DirectDeclarator
   <- ( Identifier
      / LPAR Declarator RPAR
      )

Pointer <- ( STAR )+

Spacing
   <- ( WhiteSpace )*

WhiteSpace  <- [ \n\r\t]

LongComment <- '/*' (!'*/'.)* '*/'

VOID      <- 'void'      !IdChar Spacing

Keyword
   <- ( 'void' ) !IdChar

Identifier  <- !Keyword IdNondigit IdChar* Spacing #{}

IdNondigit
   <- [a-z] / [A-Z] / [_]

IdChar
   <- [a-z] / [A-Z] / [0-9] / [_]

LPAR      <-  '('         Spacing
RPAR      <-  ')'         Spacing
STAR      <-  '*'  ![=]   Spacing
SEMI      <-  ';'         Spacing

EOT       <-  !.
```

**Comment by mingodad** [comment]
And now even smaller and with same behavior (if we remove the non referenced `LongComment` definition then it parses fine):
```
TranslationUnit <- Spacing ( Declaration / SEMI ) * EOT

Declaration <- VOID+ (STAR* Identifier)? SEMI

Spacing
   <- ( WhiteSpace )*

WhiteSpace  <- [ \n\r\t]

LongComment <- '/*' (!'*/'.)* '*/'

VOID      <- 'void'      !IdChar Spacing

Keyword
   <- ( 'void' ) !IdChar

Identifier  <- !Keyword IdNondigit IdChar* Spacing

IdNondigit
   <- [a-z] / [A-Z] / [_]

IdChar
   <- [a-z] / [A-Z] / [0-9] / [_]

STAR      <-  '*'  ![=]   Spacing
SEMI      <-  ';'         Spacing

EOT       <-  !.
```

**Comment by mingodad** [comment]
Again even smaller and with same behavior (if we remove the non referenced `LongComment` definition then it parses fine):
```
Declaration <- VOID STAR Identifier SEMI EOT

Spacing
   <- ( WhiteSpace )*

WhiteSpace  <- [ \n\r\t]

LongComment <- '/*' (!'*/'.)* '*/'

VOID      <- 'void'      !IdChar Spacing

Identifier  <- IdNondigit IdChar* Spacing

IdNondigit
   <- [a-z] / [A-Z] / [_]

IdChar
   <- [a-z] / [A-Z] / [0-9] / [_]

STAR      <-  '*'    Spacing
SEMI      <-  ';'     Spacing

EOT       <-  !.
```

**Comment by mingodad** [comment]
Using [my](https://github.com/ChrisHixon/chpeg/issues/4#issuecomment-1121062805) to output the cbytecode with and without `LongComment` I can see that the when the `LongComment` is present then the `"*"` is missing from the `peg_strings`.

With `LongComment`:
```
...
int peg_num_strings = 9;
char *peg_strings[] = {
	" \n\r\t","/*","*/","void","a-z","A-Z","_","0-9",";"
};
int peg_str_len[] = {
	4,2,2,4,3,3,1,3,1
};
...
```
Whitouth `LongCommnet`:
```
...
int peg_num_strings = 8;
char *peg_strings[] = {
	" \n\r\t","void","a-z","A-Z","_","0-9","*",";"
};
int peg_str_len[] = {
	4,4,3,3,1,3,1,1
};
...
```

**Comment by mingodad** [comment]
Following the execution with gdb I found the problem it's here:
```
int Compiler_alloc_string(CompilationUnit *cu, const unsigned char *str, int len)
{
    for (int i = 0; i < cu->bc->num_strings; ++i) {
        if (0 == strcmp(cu->bc->strings[i], str)) { ///!!! before it was memcmp(cu->bc->strings[i], str, len)
            return i;
        }
    }
...
```
With `LongComment` present we have added one string `*/` and when try to add the string `*` with length 1 then `memcmp` will match `*/` and reject to add `*`.

**Comment by ChrisHixon** [comment]
Ah! Nice find. Does that fix the bug in this issue or do you still see something like is happening in https://github.com/ChrisHixon/chpeg/issues/9 ?

**Comment by ChrisHixon** [comment]
I believe I was dealing with strings that way in case they include \0. Who knows, someone might parse binary data with PEG? :D

**Comment by mingodad** [comment]
Right now I only tested with this issue:
```
chpeg2-nb c99-mouse.peg c99-mouse.peg.pp.c
Grammar file compiled successfully. Parser returned: 19382
parse ok.
parse ok.
...
187590     14     48 |     |       JumpStatement "return yyctx;\n"
187596      1     71 |     |         WhiteSpace " "
187597      5    117 |     |         Identifier "yyctx"
187597      1    118 |     |           IdNondigit "y"
187598      1    119 |     |           IdChar "y"
187599      1    119 |     |           IdChar "c"
187600      1    119 |     |           IdChar "t"
187601      1    119 |     |           IdChar "x"
187602      0     70 |     |           Spacing ""
187603      1     71 |     |         WhiteSpace "\n"
187605      1     71 |     |       WhiteSpace "\n"
187606      0    194 |     |   EOT ""
```

**Comment by mingodad** [comment]
So a better fix would be to check if the size is equal when `memcmp` retruns 0 to be sure that they are equal !

**Comment by ChrisHixon** [comment]
This is my current fix:
```
    for (int i = 0; i < cu->bc->num_strings; ++i) {
        if (len == cu->bc->str_len[i] && 0 == memcmp(cu->bc->strings[i], str, len)) {
            return i;
        }
    }
```

**Comment by mingodad** [comment]
Just like what I was going to show you, we are in the same wave here !

**Comment by mingodad** [comment]
Here is the performance comparison with `cpp-peglib`:
```
/usr/bin/time chpeg2-nb c99-mouse.peg c99-mouse.peg.pp.c > /dev/null
Grammar file compiled successfully. Parser returned: 19390
0.62user 0.00system 0:00.62elapsed 100%CPU (0avgtext+0avgdata 10172maxresident)k
0inputs+0outputs (0major+2269minor)pagefaults 0swaps

/usr/bin/time peglint --ast c99-mouse-cpp-peglib.peg c99-mouse.peg.pp.c > /dev/null
2.06user 0.03system 0:02.10elapsed 99%CPU (0avgtext+0avgdata 76376maxresident)k
0inputs+0outputs (0major+20586minor)pagefaults 0swaps
```

**Comment by ChrisHixon** [comment]
Awesome!

**Comment by mingodad** [comment]
I think we can close this issue, but remember the lessons to figure out the problem to somehow make it easier for future users.

**Comment by ChrisHixon** [comment]
Changes are coming soon to make debugging any future issues easier.

**Comment by yhirose** [comment]
@mingodad could you test with `/usr/bin/time peglint --ast --packrat c99-mouse-cpp-peglib.peg c99-mouse.peg.pp.c > /dev/null` for better comparison? `--packrat` option should speed up cpp-peglib parsing quite a bit. I believe chpeg should still be faster than cpp-peglib though due to the byte code approach. :)

**Comment by ChrisHixon** [comment]
```
/usr/bin/time chpeg2-nb c99-mouse.peg c99-mouse.peg.pp.c > /dev/null
Grammar file compiled successfully. Parser returned: 19390
0.62user 0.00system 0:00.62elapsed 100%CPU (0avgtext+0avgdata 10172maxresident)k
0inputs+0outputs (0major+2269minor)pagefaults 0swaps
```

I've been able to get similar timing if I enable optimization with -O3 and put my laptop in performance mode (vs normal power saving mode). You can gain even more speed if you disable error tracking (compile time option); and perhaps a tiny bit more removing sanity checks. It'll still fail with errors with error tracking disabled, but it can't tell you where the error is. I suppose this could made into a runtime option.

**Comment by mingodad** [comment]
Hello @yhirose I'm enjoying your project a lot and it's on my top list for develop `peg` grammars, I know that option and for the time performance it really makes a difference but it comes with toll in memory usage.

And of course your `cpp-peglib` does a lot more utf-8, precedence climbing, better error messages, a nice playground, case insensitive literals, more repetition options, ...

```
/usr/bin/time peglint --ast --packrat c99-mouse.peg c99-mouse.peg.pp.c  > /dev/null
0.66user 0.05system 0:00.72elapsed 99%CPU (0avgtext+0avgdata 164128maxresident)k
0inputs+0outputs (0major+42892minor)pagefaults 0swaps

/usr/bin/time peglint --ast  c99-mouse.peg c99-mouse.peg.pp.c  > /dev/null
2.09user 0.01system 0:02.10elapsed 100%CPU (0avgtext+0avgdata 76364maxresident)k
0inputs+0outputs (0major+20585minor)pagefaults 0swaps
```

**Comment by ChrisHixon** [comment]
Here's a test with and without error tracking and sanity checks:

```
In Makefile
CC=clang
CFLAGS=-Wall -std=c99 -O3

% /usr/bin/time ../../examples/peg_parse_file c99-mouse.peg c99-mouse.peg.pp.c > /dev/null
Grammar file compiled successfully. Parser returned: 19382
0.63user 0.00system 0:00.64elapsed 100%CPU (0avgtext+0avgdata 17392maxresident)k
0inputs+0outputs (0major+4078minor)pagefaults 0swaps
```

```
In Makefile:
CC=clang
CFLAGS=-Wall -std=c99 -O3 -DERRORS=0 -DSANITY_CHECKS=0

% /usr/bin/time ../../examples/peg_parse_file c99-mouse.peg c99-mouse.peg.pp.c > /dev/null
Grammar file compiled successfully. Parser returned: 19382
0.55user 0.01system 0:00.56elapsed 100%CPU (0avgtext+0avgdata 17452maxresident)k
0inputs+0outputs (0major+4080minor)pagefaults 0swaps
```

**Comment by ChrisHixon** [comment]
Note that with gcc -O3-6 I don't see a noticeable difference with errors and sanity checking off. With clang I get this slight improvement.

**Comment by mingodad** [comment]
Strange that your build of `chpeg` is using more memory than mine:
- Yours   17392k
- Mine    10172k

**Comment by ChrisHixon** [comment]
That is interesting. Can you try it with latest commit I made (with the trace/debugging/misc fixes) and see if that changes anything with memory usage?

**Comment by ChrisHixon** [comment]
That's kind of odd mine uses more. I get similar memory use clang vs gcc so it's not that. Are we using the same .peg and .c files? I'm using the ones from the zip in the first comment in this issue.

So if it's not the input files, perhaps something on my machine. Different /usr/bin/time? Different kernel? Different architecture? 
Do you know a different way to get max memory usage?

```
% /usr/bin/time --version
time (GNU Time) UNKNOWN
Copyright (C) 2019 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by David Keppel, David MacKenzie, and Assaf Gordon.

# HMM, UNKNOWN, not too useful

% uname -a
Linux envy 5.17.5-arch1-1 #1 SMP PREEMPT Wed, 27 Apr 2022 20:56:11 +0000 x86_64 GNU/Linux
```
Part of CPU from sudo lshw:
``` 
         description: CPU
          product: AMD Ryzen 7 4700U with Radeon Graphics
          vendor: Advanced Micro Devices [AMD]
          physical id: 15
          bus info: cpu@0
          version: AMD Ryzen 7 4700U with Radeon Graphics
          serial: [REMOVED]
          slot: FP6
          size: 2347MHz
          capacity: 4200MHz
          width: 64 bits
```

**Comment by mingodad** [comment]
But on this message https://github.com/ChrisHixon/chpeg/issues/2#issuecomment-1123112969 unless what you're showing is a copy of mine you was getting memory usage like mine.

**Comment by ChrisHixon** [comment]
Yeah I was quoted yours there, note the exe name.

**Comment by mingodad** [comment]
Here is the files I'm using.
[c99-mouse-files.zip](https://github.com/ChrisHixon/chpeg/files/8668458/c99-mouse-files.zip)

**Comment by mingodad** [comment]
My system:
```
/usr/bin/time --version
GNU time 1.7

mingo@mingo-X550VX:~/dev/c/A_grammars/chpeg/dad$ uname -a
Linux mingo-X550VX 5.4.0-109-generic #123~18.04.1-Ubuntu SMP Fri Apr 8 09:48:52 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

description: CPU
          product: Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
          vendor: Intel Corp.
          physical id: 15
          bus info: cpu@0
          version: Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
          serial: To Be Filled By O.E.M.
          slot: U3E1
          size: 1822MHz
          capacity: 4005MHz
          width: 64 bits
          clock: 100MHz
```

**Comment by ChrisHixon** [comment]
Using these files I get these results:

```
/usr/bin/time ../../examples/peg_parse_file c99-mouse.peg c99-mouse.peg.pp.c > /dev/null
Grammar file compiled successfully. Parser returned: 19390
0.54user 0.00system 0:00.54elapsed 99%CPU (0avgtext+0avgdata 10272maxresident)k
0inputs+0outputs (0major+2273minor)pagefaults 0swaps
```
The .c file is identical. The peg file diff:
```
421c421
< Spacing
---
> Spacing {I}
537c537
< Identifier <- !Keyword IdNondigit IdChar* Spacing #{}
---
> Identifier {L} <- !Keyword IdNondigit IdChar* Spacing #{}
```
So Spacing was not being ignored on my tests using ~17MB

**Comment by mingodad** [comment]
Sorry about that, it was my fault not checking it, but at least we know it now and it's nice to see that a little touch give so much improvement.

**Comment by mingodad** [comment]
A good next challenge would be to try convert https://github.com/edubart/lpegrex/blob/main/parsers/c11.lua to `chpeg` and successfully parse `sqlite3.c` .

**Comment by ChrisHixon** [comment]
On that subject occasionally I think that these could have clearer names or explanations:

```
// rule/node flags AKA options
enum Flags {
    STOP = 1<<0,    // used - stop automatic unwrapping, forcing this node to be a container
    IGNORE = 1<<1,  // used - deletes nodes matching this identifier
    LEAF = 1<<2,    // used - collects this node and anything underneath as a final leaf (text) node
};
```
STOP is really more like "CAPTURE", it forces that node to capture (contain what is under it) and not be eliminate by unwrap.
IGNORE is ok I suppose
LEAF is more like "TERMINAL" or "TEXT"? No nodes will exist under it and it really only "contains" the text - really the match offset and length.

Unwrap is probably unclear also, but it seems similar to what https://yhirose.github.io/cpp-peglib/ does as 'optimize' AST. I'm not sure of the correct or most often used terminology for this concept. Unwrap eliminates intermediate nodes that only contain one child node. A->B->C->D reduced to D.
Any thoughts on this since you've been experimenting with so many PEG libs?

**Comment by ChrisHixon** [comment]
Perhaps we should move discussion back to the improvements thread. Can you repost improvement ideas over there?

**Comment by mingodad** [comment]
Yes of course !

**Comment by ChrisHixon** [comment]
Closing this. Fixed in https://github.com/ChrisHixon/chpeg/commit/851be688bf7640b6dee5114e4cbdb78acfb34ff8
